---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubevirt-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}  
  labels:
    {{- include "kubevirt-operator.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}        
spec:
  replicas: {{ default .Values.replicaCount "2" }}
  revisionHistoryLimit: {{ default .Values.revisionHistoryLimit "1" }}  
  selector:
    matchLabels:
      {{- include "kubevirt-operator.selectorLabels" . | nindent 6 }}         
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: {{ include "kubevirt-operator.fullname" . }}    
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubevirt-operator.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}              
    spec:
      serviceAccountName: {{ include "kubevirt-operator.serviceAccountName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}    
      containers:
      - name: virt-operator
        image: quay.io/kubevirt/virt-operator:v{{ .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent       
        command:
        - virt-operator
        args:
        - --port
        - "8443"
        - -v
        - "2"
        env:
        - name: VIRT_OPERATOR_IMAGE
          value: quay.io/kubevirt/virt-operator:v{{ .Chart.AppVersion }}
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['olm.targetNamespaces']
        - name: KUBEVIRT_VERSION
          value: v{{ .Chart.AppVersion }}
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        - containerPort: 8444
          name: webhooks
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
          timeoutSeconds: 10          
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
          timeoutSeconds: 10
        {{- with .Values.resources }}          
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /etc/virt-operator/certificates
          name: kubevirt-operator-certs
          readOnly: true
        - mountPath: /profile-data
          name: profile-data
      priorityClassName: kubevirt-cluster-critical
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      volumes:
      - name: kubevirt-operator-certs
        secret:
          optional: true
          secretName: kubevirt-operator-certs
      - emptyDir: {}
        name: profile-data
