---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "kubevirt-operator.labels" . | nindent 4 }}
{{- with .Values.config }}          
spec:
{{- toYaml . | nindent 2 }}
{{- end }}
