---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubevirt-operator.fullname" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    kubevirt.io: ""
    {{- include "kubevirt-operator.labels" . | nindent 4 }}  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubevirt-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubevirt-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}