---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubevirt-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    kubevirt.io: ""
    {{- include "kubevirt-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resourceNames:
  - kubevirt-ca
  - kubevirt-export-ca
  - kubevirt-virt-handler-certs
  - kubevirt-virt-handler-server-certs
  - kubevirt-operator-certs
  - kubevirt-virt-api-certs
  - kubevirt-controller-certs
  - kubevirt-exportproxy-certs
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch
  - patch
  - delete
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - get
  - list
  - watch
  - patch
  - delete
- apiGroups:
  - route.openshift.io
  resources:
  - routes/custom-host
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - delete
  - update
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - delete
  - update
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - kubevirt-export-ca
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch