---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubevirt-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    kubevirt.io: ""
    {{- include "kubevirt-operator.labels" . | nindent 4 }}