---
kind: ConfigMap
apiVersion: v1
metadata: 
  name: {{ printf "%s-daemon-config" (include "multus-cni.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "multus-cni.labels" . | nindent 4 }}  
data:
  daemon-config.json: |
    {
        "chrootDir": "/hostroot",
        "cniVersion": "{{ .Values.cniVersion }}",
        "logLevel": "verbose",
        "logToStderr": true,
        "cniConfigDir": "/host/etc/cni/net.d",
        "multusAutoconfigDir": "/host/etc/cni/net.d",
        "multusConfigFile": "auto",
        "socketDir": "/host/run/multus/"
    } 