---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "multus-cni.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "multus-cni.labels" . | nindent 4 }}     
spec:
  strategy:
    type: RollingUpdate  
  selector:
    matchLabels:
      {{- include "multus-cni.selectorLabels" . | nindent 6}}
  template:
    metadata:  
      labels:
        {{- include "multus-cni.labels" . | nindent 8 }}  
    spec:
      serviceAccountName: {{ include "multus-cni.serviceAccountName" . }}
      hostNetwork: true
      hostPID: true
      initContainers:
      - name: install-multus-binary
        image: ghcr.io/k8snetworkplumbingwg/multus-cni:v{{ .Chart.AppVersion }}
        command:
        - "sh"
        - "-c"
        - "cp /usr/src/multus-cni/bin/multus-shim /host/opt/cni/bin/multus-shim && cp /usr/src/multus-cni/bin/passthru /host/opt/cni/bin/passthru"
        resources:
          requests:
            cpu: "10m"
            memory: "15Mi"
        volumeMounts:
        - name: cnibin
          mountPath: /host/opt/cni/bin
          mountPropagation: Bidirectional              
        securityContext:
          privileged: true
        terminationMessagePolicy: FallbackToLogsOnError      
      containers:
      - name: kube-multus
        image: ghcr.io/k8snetworkplumbingwg/multus-cni:v{{ .Chart.AppVersion }}
        command:
        - /usr/src/multus-cni/bin/multus-daemon
        env:
        - name: MULTUS_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName        
        {{- with .Values.resources }}          
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}            
        volumeMounts:
        - name: cni
          mountPath: /host/etc/cni/net.d
        - name: cnibin
          mountPath: /opt/cni/bin
        - name: host-run
          mountPath: /host/run
        - name: host-var-lib-cni-multus
          mountPath: /var/lib/cni/multus
        - name: host-var-lib-kubelet
          mountPath: /var/lib/kubelet
          mountPropagation: HostToContainer
        - name: host-run-k8s-cni-cncf-io
          mountPath: /run/k8s.cni.cncf.io
        - name: host-run-netns
          mountPath: /run/netns
          mountPropagation: HostToContainer
        - name: multus-daemon-config
          mountPath: /etc/cni/net.d/multus.d
          readOnly: true
        - name: hostroot
          mountPath: /hostroot
          mountPropagation: HostToContainer
        - mountPath: /etc/cni/multus/net.d
          name: multus-conf-dir
        securityContext:
          privileged: true
        terminationMessagePolicy: FallbackToLogsOnError                        
      terminationGracePeriodSeconds: 10      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}     
      volumes:
      - name: cni
        hostPath:
          path: /etc/cni/net.d
      - name: cnibin
        hostPath:
          path: /opt/cni/bin
      - name: hostroot
        hostPath:
          path: /
      - name: multus-daemon-config
        configMap:
          name: {{ printf "%s-daemon-config" (include "multus-cni.fullname" .) }}
          items:
          - key: daemon-config.json
            path: daemon-config.json
      - name: host-run
        hostPath:
          path: /run
      - name: host-var-lib-cni-multus
        hostPath:
          path: /var/lib/cni/multus
      - name: host-var-lib-kubelet
        hostPath:
          path: /var/lib/kubelet
      - name: host-run-k8s-cni-cncf-io
        hostPath:
          path: /run/k8s.cni.cncf.io
      - name: host-run-netns
        hostPath:
          path: /run/netns/
      - name: multus-conf-dir
        hostPath:
          path: /etc/cni/multus/net.d                   