---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "multus-cni.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    operator.cdi.kubevirt.io: ""
    {{- include "multus-cni.labels" . | nindent 4 }}
