fullnameOverride: ""
serviceAccountName: ""
replicaCount: 2

crds:
  # Install and upgrade CRDs from normal template. If false crds will be installed according to helm rules - i.e. will not be installed :D 
  install: true
  # Keep CRDs after uninstall of this application. This will also keep the objects created with these CRDs. 
  keep: true

config:
  imagePullPolicy: IfNotPresent
  configuration:
    developerConfiguration:
      featureGates: []
  certificateRotateStrategy: {}
  customizeComponents: {}
  workloadUpdateStrategy: {}

resources: 
  requests:
    cpu: 10m
    memory: 450Mi

nodeSelector:
  kubernetes.io/os: linux

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: kubevirt.io
            operator: In
            values:
            - virt-operator
        topologyKey: kubernetes.io/hostname
      weight: 1

tolerations:
- key: CriticalAddonsOnly
  operator: Exists

