fullnameOverride: ""
serviceAccountName: ""
replicaCount: 2

config:
  imagePullPolicy: IfNotPresent
  configuration:
    developerConfiguration:
      featureGates: []
  certificateRotateStrategy: {}
  customizeComponents: {}
  workloadUpdateStrategy: {}

resources: 
  requests:
    cpu: 10m
    memory: 450Mi

nodeSelector:
  kubernetes.io/os: linux

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: kubevirt.io
            operator: In
            values:
            - virt-operator
        topologyKey: kubernetes.io/hostname
      weight: 1

tolerations:
- key: CriticalAddonsOnly
  operator: Exists

