---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cluster-network-addons-operator.fullname" . }}
  labels:
    {{- include "cluster-network-addons-operator.labels" . | nindent 4 }}  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cluster-network-addons-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "cluster-network-addons-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}