apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cluster-network-addons-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}  
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}  
  labels:
    {{- include "cluster-network-addons-operator.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}              
spec:
  replicas: {{ default .Values.replicaCount "1" }}
  revisionHistoryLimit: {{ default .Values.revisionHistoryLimit "1" }}
  selector:
    matchLabels:
      {{- include "cluster-network-addons-operator.selectorLabels" . | nindent 6 }}   
  strategy:
    type: Recreate
  template:
    metadata:
      name: {{ include "cluster-network-addons-operator.fullname" . }}   
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cluster-network-addons-operator.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}  
    spec:
      serviceAccountName: {{ include "cluster-network-addons-operator.serviceAccountName" . }}  
      priorityClassName: system-cluster-critical
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}            
      {{- $images := include "cluster-network-addons-operator.addonImages" . | fromYaml }}
      containers:
      - name: cluster-network-addons-operator
        image: quay.io/kubevirt/cluster-network-addons-operator:v{{ .Chart.AppVersion }}
        imagePullPolicy: Always
        env:
        - name: MULTUS_IMAGE
          value: {{ $images.multus }}
        - name: MULTUS_DYNAMIC_NETWORKS_CONTROLLER_IMAGE
          value: {{ $images.multusDynamicNetworksController }}
        - name: LINUX_BRIDGE_IMAGE
          value: {{ $images.linuxBridge }}
        - name: LINUX_BRIDGE_MARKER_IMAGE
          value: {{ $images.linuxBridgeMarker }}
        - name: OVS_CNI_IMAGE
          value: {{ $images.ovsCNI }}
        - name: KUBEMACPOOL_IMAGE
          value: {{ $images.kubeMacPool }}
        - name: MACVTAP_CNI_IMAGE
          value: {{ $images.macVTapCNI }}
        - name: KUBE_SECONDARY_DNS_IMAGE
          value: {{ $images.kubeSecondaryDNS }}
        - name: CORE_DNS_IMAGE
          value: {{ $images.coreDNS }}
        - name: KUBEVIRT_IPAM_CONTROLLER_IMAGE
          value: {{ $images.kubeVirtIPAMController }}
        - name: OPERATOR_IMAGE
          value: quay.io/kubevirt/cluster-network-addons-operator:v{{ .Chart.AppVersion }}
        - name: OPERATOR_NAME
          value: cluster-network-addons-operator
        - name: OPERATOR_VERSION
          value: {{ .Chart.AppVersion }}
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERAND_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
        - name: MONITORING_NAMESPACE
          value: openshift-monitoring
        - name: MONITORING_SERVICE_ACCOUNT
          value: prometheus-k8s
        - name: RUNBOOK_URL_TEMPLATE
          value: https://kubevirt.io/monitoring/runbooks/%s
        - name: CNAO_LOG_LEVEL
          value: {{ .Values.logLevel | quote }}          
        ports:        
        - name: healthprobe          
          containerPort: 8081
          protocol: TCP    
        - name: metrics
          containerPort: 8443
          protocol: TCP                  
        {{- with .Values.resources }}          
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthprobe
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthprobe
          initialDelaySeconds: 5
          periodSeconds: 10                  
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        terminationMessagePolicy: FallbackToLogsOnError
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}        
