---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }} 
  annotations:
    helm.sh/resource-policy: keep
  labels:
    name: {{ .Release.Namespace }} 
    openshift.io/cluster-monitoring: "true"