---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-network-addons-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "cluster-network-addons-operator.labels" . | nindent 4 }}