fullnameOverride: ""
serviceAccountName: ""
replicaCount: 2
revisionHistoryLimit: 2

resources: 
  requests:
    cpu: 50m
    memory: 30Mi

rbacProxyResources:
  requests:
    cpu: 10m
    memory: 20Mi

nodeSelector:
  kubernetes.io/os: linux

affinity: {}    
