---
apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
metadata:
  name: cdi
  namespace: {{ .Release.Namespace }}
  {{- if .Values.crds.keep }}
  annotations:  
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
    {{- include "cdi-operator.labels" . | nindent 4 }}
{{- with .Values.config }}          
spec:
{{- toYaml . | nindent 2 }}
{{- end }}
