---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cdi-operator.fullname" . }}
  labels:
    operator.cdi.kubevirt.io: ""
    {{- include "cdi-operator.labels" . | nindent 4 }}  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cdi-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "cdi-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}