---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cdi-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-operator
    cdi.kubevirt.io: ""
    {{- include "cdi-operator.labels" . | nindent 4 }} 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cdi-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "cdi-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}    