---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cdi-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    operator.cdi.kubevirt.io: ""
    {{- include "cdi-operator.labels" . | nindent 4 }}
