---
name: helm-build
permissions:
  packages: write
  contents: read
on:
  push:
    branches:
    - master
    - dev
    tags:
    - '*-v[0-9]+.[0-9]+.[0-9]+'
env:
  TAG: ${{ github.ref_name }}
jobs:

  build-branch:
    if:
      contains('
        refs/heads/dev
        refs/heads/master
      ', github.ref)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get 'latest' chart tag
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          IMAGE_TAG="latest"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      - name: Get 'dev' chart tag          
        if: ${{ github.ref == 'refs/heads/dev' }}
        run: |
          IMAGE_TAG="dev"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      - name: helm lint
        run: |
          for chart in charts/*/; do
            helm lint charts/$chart
          done        
      - name: helm login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u $ --password-stdin
      - name: helm package
        run: |
          for chart in charts/*/; do
            helm package charts/$chart --version $IMAGE_TAG
          done         
      - name: helm push
        if: ${{ github.event_name == 'push' }}
        run: |
          for chart in charts/*/; do
            helm push $chart-$IMAGE_TAG.tgz oci://ghcr.io/${{ github.repository_owner }}
          done         

  build-tag:
    if: ${{ github.ref_type == 'tag' }}  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Extract chart name and version
        id: extract
        run: |
          CHART_NAME="${TAG%-v*}"
          IMAGE_TAG="v${TAG#*-v}"
          echo "CHART_NAME=$CHART_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      - name: helm lint
        run: |
          helm lint charts/$CHART_NAME
      - name: helm login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u $ --password-stdin
      - name: helm package
        run: |
          helm package charts/$CHART_NAME --version $IMAGE_TAG
      - name: helm push
        if: ${{ github.event_name == 'push' }}
        run: |
          helm push $CHART_NAME-$IMAGE_TAG.tgz oci://ghcr.io/${{ github.repository_owner }}
